kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-devops1
  namespace: default
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged      #Default ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: wcp:10.193.132.129:devops1@vsphere.local            #sso:<username>@<domain>
  apiGroup: rbac.authorization.k8s.io
