apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-ui
  namespace: 99994-990004-1001-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-ui
  template:
    metadata:
      labels:
        app: app1-ui
        enableIdentityHelper: "true"
    spec:
      securityContext:
        runAsUser: 99
        fsGroup: 99
      containers:
      - name: app1-ui
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        livenessProbe:
          httpGet:
            path: /actuator/keepalive
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 1