apiVersion: v1
kind: Namespace
metadata:
  name: 99992-990002-1001-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: 99992-990002-1002-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: 99992-990002-1003-dev