kind: Namespace
apiVersion: v1
metadata:
  name: 99999-9000-1002-prod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: management-ui 
  namespace: 99999-9000-1002-prod 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: 99999-9000-1002-prod 
    spec:
      containers:
      - name: management-ui
        image: calico/star-collect:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 900001
---
apiVersion: v1
kind: Service
metadata:
  name: management-ui 
  namespace: 99999-9000-1002-prod 
spec:
  type: NodePort
  ports:
  - port: 900001 
    targetPort: 900001
    nodePort: 30003
  selector:
    namespace: 99999-9000-1002-prod 