kind: Namespace
apiVersion: v1
metadata:
  name: 99993-990003-1003-dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db 
  namespace: 99993-990003-1003-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: 99993-990003-1003-dev 
    spec:
      containers:
      - name: db 
        image: calico/star-probe:v0.1.0
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=1521
        - --http-probe-seconds=10
        - --urls=http://client.99990-900002-1002-dev:9000/status,http://psaas.99991-900001-900001-dev:443/status,http://web.99994-990004-1001-dev:443/status,http://app.99994-990004-1002-dev:9443/status,http://client.99990-900002-1002-prod:9000/status,http://psaas.99991-900001-900001-prod:443/status,http://web.99994-990004-1001-prod:443/status,http://app.99994-990004-1002-prod:9443/status,,http://db.99993-990003-1003-prod:1521/status
        ports:
        - containerPort: 1521 
---
apiVersion: v1
kind: Service
metadata:
  name: db 
  namespace: 99993-990003-1003-dev
spec:
  ports:
  - port: 1521
    targetPort: 1521 
  selector:
    namespace: 99993-990003-1003-dev